Dec 06 12:27:14,500  INFO ClassPathXmlApplicationContext:578 - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@5fcfe4b2: startup date [Thu Dec 06 12:27:14 MYT 2018]; root of context hierarchy
Dec 06 12:27:14,533  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [plate-service.xml]
Dec 06 12:27:14,614  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [plate-persistence.xml]
Dec 06 12:27:14,720  WARN ClassPathXmlApplicationContext:546 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.plate.home.persistence.HomeDaoImpl] for bean with name 'home' defined in class path resource [plate-persistence.xml]; nested exception is java.lang.ClassNotFoundException: org.plate.home.persistence.HomeDaoImpl
Dec 06 12:28:24,634  INFO ClassPathXmlApplicationContext:578 - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@5fcfe4b2: startup date [Thu Dec 06 12:28:24 MYT 2018]; root of context hierarchy
Dec 06 12:28:24,665  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [plate-service.xml]
Dec 06 12:28:24,744  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [plate-persistence.xml]
Dec 06 12:28:24,847  WARN ClassPathXmlApplicationContext:546 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.plate.home.persistence.HomeImpl] for bean with name 'home' defined in class path resource [plate-persistence.xml]; nested exception is java.lang.ClassNotFoundException: org.plate.home.persistence.HomeImpl
Dec 06 12:29:45,538  INFO ClassPathXmlApplicationContext:578 - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@5fcfe4b2: startup date [Thu Dec 06 12:29:45 MYT 2018]; root of context hierarchy
Dec 06 12:29:45,568  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [plate-service.xml]
Dec 06 12:29:45,647  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [plate-persistence.xml]
Dec 06 12:29:45,776  WARN ClassPathXmlApplicationContext:546 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.plate.services.Services] for bean with name 'services' defined in class path resource [plate-service.xml]; nested exception is java.lang.ClassNotFoundException: org.plate.services.Services
Dec 06 12:31:07,629  INFO ClassPathXmlApplicationContext:578 - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@5fcfe4b2: startup date [Thu Dec 06 12:31:07 MYT 2018]; root of context hierarchy
Dec 06 12:31:07,660  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [plate-service.xml]
Dec 06 12:31:07,739  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [plate-persistence.xml]
Dec 06 12:31:07,845  WARN ClassPathXmlApplicationContext:546 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.plate.services.Service] for bean with name 'services' defined in class path resource [plate-service.xml]; nested exception is java.lang.ClassNotFoundException: org.plate.services.Service
Dec 06 12:31:38,672  INFO ClassPathXmlApplicationContext:578 - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@5fcfe4b2: startup date [Thu Dec 06 12:31:38 MYT 2018]; root of context hierarchy
Dec 06 12:31:38,702  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [plate-service.xml]
Dec 06 12:31:38,782  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [plate-persistence.xml]
Dec 06 12:31:38,951 ERROR BaseUserDaoImpl:40 - Could not execute : Could not get JDBC Connection; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (FATAL: database "plate" does not exist)
org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (FATAL: database "plate" does not exist)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:630)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:909)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:970)
	at org.plate.user.persistence.BaseUserDaoImpl.store(BaseUserDaoImpl.java:26)
	at org.plate.user.test.TestBaseUser.main(TestBaseUser.java:31)
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (FATAL: database "plate" does not exist)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549)
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
	... 5 more
Caused by: org.postgresql.util.PSQLException: FATAL: database "plate" does not exist
	at org.postgresql.core.v3.ConnectionFactoryImpl.readStartupMessages(ConnectionFactoryImpl.java:712)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:215)
	at org.postgresql.Driver.makeConnection(Driver.java:406)
	at org.postgresql.Driver.connect(Driver.java:274)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
	... 9 more
Dec 06 12:35:21,428  INFO ClassPathXmlApplicationContext:578 - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@5fcfe4b2: startup date [Thu Dec 06 12:35:21 MYT 2018]; root of context hierarchy
Dec 06 12:35:21,457  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [plate-service.xml]
Dec 06 12:35:21,537  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [plate-persistence.xml]
Dec 06 12:35:22,005  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [org/springframework/jdbc/support/sql-error-codes.xml]
Dec 06 12:35:22,035  INFO SQLErrorCodesFactory:126 - SQLErrorCodes loaded: [DB2, Derby, H2, HSQL, Informix, MS-SQL, MySQL, Oracle, PostgreSQL, Sybase, Hana]
Dec 06 12:35:22,085 ERROR BaseUserDaoImpl:40 - Could not execute : PreparedStatementCallback; SQL [INSERT INTO baseuser (id,email,contact,phone,password) VALUES (?,?,?,?,?)]; The column index is out of range: 11, number of columns: 5.; nested exception is org.postgresql.util.PSQLException: The column index is out of range: 11, number of columns: 5.
org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [INSERT INTO baseuser (id,email,contact,phone,password) VALUES (?,?,?,?,?)]; The column index is out of range: 11, number of columns: 5.; nested exception is org.postgresql.util.PSQLException: The column index is out of range: 11, number of columns: 5.
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:102)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:660)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:909)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:970)
	at org.plate.user.persistence.BaseUserDaoImpl.store(BaseUserDaoImpl.java:26)
	at org.plate.user.test.TestBaseUser.main(TestBaseUser.java:31)
Caused by: org.postgresql.util.PSQLException: The column index is out of range: 11, number of columns: 5.
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:63)
	at org.postgresql.core.v3.SimpleParameterList.setStringParameter(SimpleParameterList.java:126)
	at org.postgresql.jdbc.PgPreparedStatement.bindString(PgPreparedStatement.java:1096)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:369)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:353)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.setString(DelegatingPreparedStatement.java:135)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.setString(DelegatingPreparedStatement.java:135)
	at org.plate.user.persistence.BaseUserDaoImpl$1.setValues(BaseUserDaoImpl.java:34)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:914)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:909)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:644)
	... 4 more
Dec 06 12:36:01,278  INFO ClassPathXmlApplicationContext:578 - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@5fcfe4b2: startup date [Thu Dec 06 12:36:01 MYT 2018]; root of context hierarchy
Dec 06 12:36:01,309  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [plate-service.xml]
Dec 06 12:36:01,388  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [plate-persistence.xml]
Dec 06 12:36:01,941  INFO TestBaseUser:35 - org.plate.user.BaseUser@77e4c80f
Dec 06 12:36:01,941  INFO TestBaseUser:37 - Done
Dec 06 12:44:06,843  INFO ClassPathXmlApplicationContext:578 - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@5fcfe4b2: startup date [Thu Dec 06 12:44:06 MYT 2018]; root of context hierarchy
Dec 06 12:44:06,874  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [plate-service.xml]
Dec 06 12:44:06,955  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [plate-persistence.xml]
Dec 06 12:44:07,541  INFO TestBaseUser:36 - BaseUser [id=1a41d157-3470-457c-9a8f-bbb275ae4f5a, contact=pmk, email=pmk@test.com, phone=0102202005, password=88888888, enabled=false]
Dec 06 12:44:07,551  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [org/springframework/jdbc/support/sql-error-codes.xml]
Dec 06 12:44:07,582  INFO SQLErrorCodesFactory:126 - SQLErrorCodes loaded: [DB2, Derby, H2, HSQL, Informix, MS-SQL, MySQL, Oracle, PostgreSQL, Sybase, Hana]
Dec 06 12:44:07,589 ERROR BaseUserDaoImpl:105 - Could not execute : PreparedStatementCallback; SQL [UPDATE baseuser SET email=?,contact=?,phone=?,password=?,enabled=? WHERE id=?]; No value specified for parameter 6.; nested exception is org.postgresql.util.PSQLException: No value specified for parameter 6.
org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [UPDATE baseuser SET email=?,contact=?,phone=?,password=?,enabled=? WHERE id=?]; No value specified for parameter 6.; nested exception is org.postgresql.util.PSQLException: No value specified for parameter 6.
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:102)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:660)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:909)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:970)
	at org.plate.user.persistence.BaseUserDaoImpl.update(BaseUserDaoImpl.java:91)
	at org.plate.user.test.TestBaseUser.main(TestBaseUser.java:39)
Caused by: org.postgresql.util.PSQLException: No value specified for parameter 6.
	at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:225)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:190)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:161)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:133)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:916)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:909)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:644)
	... 4 more
Dec 06 12:46:33,360  INFO ClassPathXmlApplicationContext:578 - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@5fcfe4b2: startup date [Thu Dec 06 12:46:33 MYT 2018]; root of context hierarchy
Dec 06 12:46:33,392  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [plate-service.xml]
Dec 06 12:46:33,472  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [plate-persistence.xml]
Dec 06 12:46:34,024  INFO TestBaseUser:36 - BaseUser [id=b870cf75-0fba-47c6-a3ed-ce5d072f5d52, contact=pmk, email=pmk@test.com, phone=0102202005, password=88888888, enabled=false]
Dec 06 12:46:34,033  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [org/springframework/jdbc/support/sql-error-codes.xml]
Dec 06 12:46:34,065  INFO SQLErrorCodesFactory:126 - SQLErrorCodes loaded: [DB2, Derby, H2, HSQL, Informix, MS-SQL, MySQL, Oracle, PostgreSQL, Sybase, Hana]
Dec 06 12:46:34,072 ERROR BaseUserDaoImpl:106 - Could not execute : PreparedStatementCallback; SQL [UPDATE baseuser SET email=?,contact=?,phone=?,password=?,enabled=? WHERE id=?]; No value specified for parameter 6.; nested exception is org.postgresql.util.PSQLException: No value specified for parameter 6.
org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [UPDATE baseuser SET email=?,contact=?,phone=?,password=?,enabled=? WHERE id=?]; No value specified for parameter 6.; nested exception is org.postgresql.util.PSQLException: No value specified for parameter 6.
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:102)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:660)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:909)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:970)
	at org.plate.user.persistence.BaseUserDaoImpl.update(BaseUserDaoImpl.java:91)
	at org.plate.user.test.TestBaseUser.main(TestBaseUser.java:39)
Caused by: org.postgresql.util.PSQLException: No value specified for parameter 6.
	at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:225)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:190)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:161)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:133)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:916)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:909)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:644)
	... 4 more
Dec 06 12:47:26,727  INFO ClassPathXmlApplicationContext:578 - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@5fcfe4b2: startup date [Thu Dec 06 12:47:26 MYT 2018]; root of context hierarchy
Dec 06 12:47:26,758  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [plate-service.xml]
Dec 06 12:47:26,840  INFO XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [plate-persistence.xml]
Dec 06 12:47:27,412  INFO TestBaseUser:36 - BaseUser [id=0431f2bd-4536-4928-a57b-45523d42d74a, contact=pmk, email=pmk@test.com, phone=0102202005, password=88888888, enabled=false]
Dec 06 12:47:27,419  INFO TestBaseUser:43 - BaseUser [id=0431f2bd-4536-4928-a57b-45523d42d74a, contact=pmk, email=pmk@test.com, phone=0102202005, password=88888888, enabled=true]
Dec 06 12:47:27,419  INFO TestBaseUser:45 - Done
